### PR TITLE
done

### PR DESCRIPTION
**Pull request by RAJEEVKUMAR9598**

### CODE REVIEW

**Review by anupam-kumar-krishnan — CHANGES_REQUESTED** [review]
Please check before committing the code
And then raise a PR

Still your one code matrix.cpp is not in the specified folder
image

It's outside the folder
And please don't make another PR
Correct this PR itself
Correct this and I'll merge you PR

**Comment by RAJEEVKUMAR9598** [comment]
OKK SIR SORRY.

**Comment by anupam-kumar-krishnan** [comment]
Need not to say sorry
Just correct this
And I'll merge

**Review by anupam-kumar-krishnan — CHANGES_REQUESTED** [review]
image
Still outside
Move the matrix.cpp in the folder not matrix_multiply
Your matrix_multiply is at correct location

**Review by anupam-kumar-krishnan — APPROVED** [review]

**Comment by anupam-kumar-krishnan** [comment]
I have merged your PR
But still, Only merging the PR will not help

No hate, but If you could have done it then today you would have learned folder structuring

Anyways 
**_Thank you for contributing_** 💫✨
And _**Star**_ _this repository if you like_

**Pull request merged**
