### PR TITLE
Create doubly.cpp

### PR DESCRIPTION
**Pull request by Sulagnaaa**
operations in doubly linked list

### CODE REVIEW

**Comment by Sulagnaaa** [comment]
please merge my pull request on operations in doubly linked list

**Review by anupam-kumar-krishnan — CHANGES_REQUESTED** [review]
Add your code into specific folder that it belongs to

**Comment by Sulagnaaa** [comment]
added new file in the specific folder, please check for the same!

**Review by anupam-kumar-krishnan — CHANGES_REQUESTED** [review]
You have committed the file idle, rather place it in Linked List folder

**Please Check before committing**
image

**Pull request closed without merging**
