### PR TITLE
Added codes of Start51 and August Long Challenge

### PR DESCRIPTION
**Pull request by Swapneel-02**

### CODE REVIEW

**Review by anupam-kumar-krishnan — APPROVED** [review]

**Comment by anupam-kumar-krishnan** [comment]
Star this repository if you liked 🌟
And Thank you for your contribution ✨💫🙏

**Comment by Swapneel-02** [comment]
But it's showing excluded in the hacktoberfest site.

**Comment by anupam-kumar-krishnan** [comment]
Don't know the reason
But I have followed each and every guideline of making an open-source repository to participate in hacktoberfest.

**Comment by Swapneel-02** [comment]
So should I try to commit again?

**Comment by anupam-kumar-krishnan** [comment]
No actually I searched about it
What I got is that when someone report the repository
Then it'll show as excluded
I think this is what happened
So better not to commit again

**Comment by Swapneel-02** [comment]
Okay got it. No problem.

**Comment by Swapneel-02** [comment]
Thanks.

**Pull request merged**
