### PR TITLE
Added ModularExponentiation.cpp

### PR DESCRIPTION
**Pull request by Abhiram-J**
Added Modular Exponentiation Algorithm
Link to a practise problem is also mentioned in the file

Thank you !
Happy Hacktoberfest @anupam-kumar-krishnan !

### CODE REVIEW

**Comment by Abhiram-J** [comment]
Is there anything else I should add ?

**Comment by Abhiram-J** [comment]
Any merging issues @anupam-kumar-krishnan ?

**Comment by anupam-kumar-krishnan** [comment]
Hi, Abhiram
No problem in merging but people are getting that this repo which I have is excluded
That's why

**Comment by Abhiram-J** [comment]
Oh thanks for letting me know this. 
Its fine if repo is excluded atleast I am contributing to your repository :)

**Review by anupam-kumar-krishnan — APPROVED** [review]

**Pull request merged**
